import PptxGenJS from "pptxgenjs";

export async function generateMedicalPpt(content: string, title?: string): Promise<Buffer> {
  const pptx = new PptxGenJS();
  
  // Presentation properties
  pptx.author = "Medchat Medical AI";
  pptx.company = "Medchat";
  pptx.revision = "1";
  pptx.subject = "Medical Notes Export";
  pptx.title = title || "Clinical Notes & Summary";

  // Create Master Slide Layout
  pptx.defineSlideMaster({
    title: "MEDCHAT_MASTER",
    bkgd: "FFFFFF",
    objects: [
      { rect: { x: 0, y: 0, w: "100%", h: 0.6, fill: { color: "0F766E" } } },
      { text: { text: "MEDCHAT - Medical AI", options: { x: 0.2, y: 0.1, w: 4, h: 0.4, color: "FFFFFF", fontSize: 14, bold: true } } },
      { text: { text: "Generated by @MedchatBot", options: { x: "70%", y: 0.1, w: 3, h: 0.4, color: "FFFFFF", fontSize: 10, align: "right" } } }
    ],
    slideNumber: { x: "90%", y: "95%", color: "0F766E", fontSize: 10 }
  });

  // Slide 1: Title Slide
  const slide1 = pptx.addSlide({ masterName: "MEDCHAT_MASTER" });
  slide1.addText(title || "Medchat Clinical Notes", {
    x: 1, y: 2, w: 8, h: 1.5,
    fontSize: 32,
    bold: true,
    color: "0F766E",
    align: "center"
  });
  slide1.addText(new Date().toLocaleDateString(), {
    x: 1, y: 3.5, w: 8, h: 0.5,
    fontSize: 16,
    color: "64748B",
    align: "center"
  });

  // Clean the markdown content
  const cleanContent = content
    .replace(/\\*/g, '')
    .replace(/\\_/g, '')
    .replace(/#/g, '')
    .replace(/`/g, '');

  // Simple splitting by double newline to create paragraphs/bullet points
  const sections = cleanContent.split(/\n{2,}/);

  let currentSlide = pptx.addSlide({ masterName: "MEDCHAT_MASTER" });
  let yPos = 1;

  for (const section of sections) {
    const trimmed = section.trim();
    if (!trimmed) continue;

    // Estimate height needed (rough approximation: 1 inch per ~120 chars)
    const estimatedHeight = Math.max(0.5, Math.ceil(trimmed.length / 100) * 0.4);

    if (yPos + estimatedHeight > 5) {
      currentSlide = pptx.addSlide({ masterName: "MEDCHAT_MASTER" });
      yPos = 1;
    }

    currentSlide.addText(trimmed, {
      x: 0.5, y: yPos, w: 9, h: estimatedHeight,
      fontSize: 14,
      color: "333333",
      valign: "top"
    });

    yPos += estimatedHeight + 0.2;
  }

  // Generate buffer
  return Buffer.from((await pptx.write({ outputType: "arraybuffer" })) as ArrayBuffer);
}
